import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
} from '@clerk/nextjs'
import { Provider } from "@radix-ui/react-tooltip";

export const metadata: Metadata = {
  title: "Ai Video Course",
  description: "Generated by create next app",
};
const AppFont = DM_Sans({subsets: ["latin"],});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={AppFont.className}
      >  <Provider>
        {children}
        </Provider>
      </body>
    </html>
    </ClerkProvider>
  );
}
